### ISSUE TITLE
unable to open PDF with PHP7

### ISSUE THREAD

**Issue by digitalkaoz** [mkoppanen/imagick#108]
Hey im unable to a PDF file with `phpseven branch` on `PHP7.0-RC1`:

from commandline it works:

`convert https://www.iscp.ie/sites/default/files/pdf-sample.pdf cli.png` works perfectly

from php it fails

```php
$image = new Imagick('https://www.iscp.ie/sites/default/files/pdf-sample.pdf');
```

throws `ImagickException: Failed to read the file`

Although it works for images, so its not an Imagick Installtion issue i guess

i needed to compile it by hand, as there are no packages available yet...

```
git clone https://github.com/mkoppanen/imagick.git
git checkout origin/phpseven
phpize
./configure
make
```

```
$ php --info |grep imagick
Additional .ini files parsed => /usr/local/etc/php/7.0/conf.d/ext-imagick.ini,
imagick
imagick module => enabled
imagick module version => @PACKAGE_VERSION@
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
imagick.locale_fix => 0 => 0
imagick.progress_monitor => 0 => 0
imagick.skip_version_check => 0 => 0
```
any hints what might be wrong? 

PS i know, using to many RCs might not be stable ;)

**Comment by Danack** [comment]
Can you download the file from the remote site and try opening it locally?

I can't think what would have broken....I'll try and fire up the old VM later to investigate, but it might be some help if you can install `strace` and find if there is a system call that is breaking by running:

strace /usr/bin/php testScript.php

*warning* That does have some capability of putting secrets (e.g. deploy keys) into the output that you might prefer not to share, so be careful when posting the output.

I think that should show either that:

i) Some system call is failing in 7 that is passing in 5.x

or

ii) The system calls are the same, and the issue is in just the extension code.



And just to be clear, opening files directly from a like:

> $image = new Imagick('https://www.iscp.ie/sites/default/files/pdf-sample.pdf');

is just a terrible idea. You would be much better off downloading the file with curl or any other library that is designed for doing that well, rather than doing it through Imagick/ImageMagick.

**Comment by digitalkaoz** [comment]
i tried it with local files, i made the url version just for the sake of the example

**Comment by Danack** [comment]
So to be clear, it fails with the local file as well?

And it can open other image types on your system?

**Comment by digitalkaoz** [comment]
exactly

**Comment by digitalkaoz** [comment]
even with `readImageBlob ` or with streams and file_handles

**Comment by Danack** [comment]
So, I got around to testing this and I cannot reproduce the issue. Using the PDF from the link above and this code through the PHP CLI:

```
$imagick = new Imagick("./pdf-sample.pdf");

$imagick->setImageFormat("png");
$count = 0;
foreach ($imagick as $page) {
	$page->writeImage("./output_$count.png");
	$count++;
}
```

The output image is below.

I have a suspicion that this is going to be something peculiar to your system rather than a bug e.g. a permissions issue or other error on files when the PDF reading delegate is run.

Can you run the script above through strace i.e.

strace -f -F php pdfCheck.php > debug.txt 2>&1

which will spit out a huge chunk stuff. On my system the line where the ghostscript delegate is being called succesfully is:

> [pid 27475] execve("/usr/bin/gs", ["gs", "-q", "-dQUIET", "-dSAFER", "-dBATCH", "-dNOPAUSE", "-dNOPROMPT", "-dMaxBitmap=500000000", "-dAlignToPixels=0", "-dGridFitTT=2", "-sDEVICE=pngalpha", "-dTextAlphaBits=4", "-dGraphicsAlphaBits=4", "-r72x72", "-sOutputFile=/tmp/magick-27474yk"..., "-f/tmp/magick-27474xqlYt7Z52XFF", ...], [/* 22 vars */]) = 0

Whatever is going wrong is very likely to leave an error message in the debug output produced by strace. If you can't figure it out yourself, please post it.

btw it is possible for strace to include keys or other app details that you might not want to share, so you should check it before posting it on the internet.

![output_0](https://cloud.githubusercontent.com/assets/1505719/9976730/10730938-5edc-11e5-80ed-d4e6de163f83.png)

**Comment by digitalkaoz** [comment]
mh i guess we can close that (i now have `PHP7-RC2` and recompiled the extension) as your minified example works here too.
