### ISSUE TITLE
colorizeImage uses wrong opacity value

### ISSUE THREAD

**Issue by isage** [mkoppanen/imagick#119]
This is easy to confirm by comparing output of `convert ... -fill "#ff0000" -colorize 20% ...` and `colorizeImage("#ff0000", 0.2)`

According to [IM authors](http://www.imagemagick.org/discourse-server/viewtopic.php?f=6&t=8418&p=126669#p25842) you should actually use **color** as opacity value.

**Comment by Danack** [comment]
Okay, it's fixed in master and will be in 3.4.0RC3 soon. The signature for the function is now.

    Imagick::colorizeImage($color, $opacity, $legacy = false);

where:

* $color is the color applied. 

* $opacity aka strength is the amount that each pixel is colored by. Gray colors should be used to apply the effect equally to all channels. e.g. `RGB(20, 20, 20)` or probably `gray(50%)`

* $legacy is a flag to whether to use the old behaviour. It defaults to false, i.e. the new correct behaviour. This flag will be removed at some point in the future.
