### ISSUE TITLE
How to use Imagick on phpseven

### ISSUE THREAD

**Issue by kocoten1992** [mkoppanen/imagick#129]
There is vaguely a guide to use/install Imagick on php7

Currently using hhvm, once hhvm install, everything fall into place, no need to thought about Imagick, just work.

Don't know what option I could have to ask too (I guess: self compile it or use php7 branch) but really don't know what to do after download .zip file imagick-phpseven :8ball: 

Is there a guide for this, thank you so much.

**Comment by Danack** [comment]
The easiest way, if you have PECL built, is to do:

    pecl install imagick-3.4.0RC2

If you don't have PECL you should be able to install on most linux distros by just doing

```
cd /tmp
wget http://pecl.php.net/get/imagick-3.4.0RC2.tgz
tar xvzf imagick-3.4.0RC2.tgz
cd imagick-3.4.0RC2
phpize
./configure
make install
```

And then adding `extension=imagick.so` to the relevant php.ini file. If configure complains about not being able to find ImageMagick, you can tell it exactly where it is like `./configure --libdir=/usr/lib64`

**Comment by nivv** [comment]
I made a guide for Ubuntu 14.04, can be found [here](https://gist.github.com/nivv/5d9a12af5472b91606e6)

**Comment by MalikyarAbdullah** [comment]
Thanks. that did it.

**Comment by carlwgeorge** [comment]
Once there is a stable release compatible with PHP7, the [IUS](https://ius.io) project [plans to create RPM packages of this module](https://github.com/iuscommunity/wishlist/issues/37) for RHEL/CentOS 6 and 7.

**Comment by Danack** [comment]
@carlwgeorge I try to keep Imagick stable. 

I am intrigued to hear your strategy with regard to ImageMagick itself.

**Comment by carlwgeorge** [comment]
We aren't PHP developers, so we rely on upstream projects' definition of "stable".  My previous statement wasn't a judgement of the quality of the software, rather just an observation of the releases on the [pecl module page](https://pecl.php.net/package/imagick).  We are looking forward to the final release of 3.4.0 so we can package it up for our users.

As far as packaging ImageMagick itself, IUS builds packages [based on user requests](https://ius.io/Contributing/#new-package-request).  We haven't had any requests for a newer version of ImageMagick than the stock RHEL version.  It is possible that we might need to in the future as a build requirement of the pecl module.  The current base versions in RHEL have been sufficient so far.  EL6 ImageMagick did just get [rebased from 6.5.4.7 to 6.7.2.7](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html-single/6.7_Technical_Notes/index.html#package-ImageMagick).  EL7 has 6.7.8.9.  Ideally the PHP module can be kept compatible with 6.7.2.7+ so that way we can build against the stock version of ImageMagick on both EL6 and EL7.

**Comment by povrazor** [comment]
Hi. Is the "phpseven" branch still required, or is PHP 7 support in mainline now? I didn't exactly see a commit that was particularly clear about this.

Thanks

**Comment by Danack** [comment]
Hi @povrazor - the phpseven branch is no longer required, I should probably delete it as master compile against PHP 5.x and 7.

For most people, installing it through "pecl install imagick" should work, regardless of whether they are on 5.x or 7.
