### ISSUE TITLE
Weird white noise when converting .eps file on php7

### ISSUE THREAD

**Issue by vedmant** [mkoppanen/imagick#137]
Hi, I have weird problem here, we need to convert .eps files to .png, and when I upgraded to php7 it generates some weird noise on result picture http://screencast.com/t/rRtjTTf5B http://screencast.com/t/wgATl29POYN . Which is not happening when I switch to php56, http://screencast.com/t/kuOInzuxE. 

The actual code I use is:

    header("Content-type: image/png");
    
    $transparentPixel = new \ImagickPixel('transparent');
    $mImage = new \Imagick();
    $mImage->setResolution(200, 200);
    $mImage->setBackgroundColor($transparentPixel);
    $mImage->readImage('myfile.eps');
    
    $mImage->setImageFormat("png32");
    echo $mImage->getImageBlob();

Attache example file.
[805174.eps.zip](https://github.com/mkoppanen/imagick/files/104283/805174.eps.zip)

**Comment by Danack** [comment]
The good news is that it's not my fault. The bad news is that you've (almost certainly) encountered a memory corruption problem in ImageMagick.

Can you make sure that you're using the lastest (or at least recent) version of ImageMagick on the machine that is showing the corruption?

Then, if you're on a Linux box can you install valgrind and test the script with:

    valgrind /usr/local/bin/php test.php

or the appropriate path for PHP. You'll almost certainly see it complaining about invalid memory accesses. Could you also test against just the convert program that ImageMagick provides:

    valgrind convert myfile.eps output.png

**Comment by vedmant** [comment]
Indeed it was older version of ImageMagick, I upgraded it to the latest version. However the issue is still there.

I attached valgrind reports.
[convert.txt](https://github.com/mkoppanen/imagick/files/104450/convert.txt)
[php56.txt](https://github.com/mkoppanen/imagick/files/104451/php56.txt)
[php70.txt](https://github.com/mkoppanen/imagick/files/104449/php70.txt)

**Comment by Danack** [comment]
Ok...what you'll need to do is report it upstream at https://github.com/ImageMagick/ImageMagick . There's not going to be anything I can help you with inside Imagick.

>  it appears only with php7.

Yeah.....this is why invalid memory accesses need to be treated as bugs, even if they don't manifest as a problem on certain machines.

What happens is that they 'work' on some machine due to the memory being set to a particular state by other parts of the program. Then on someone else's machine, or when the memory access is changed dramatically (like it has been for PHP 5.6 -> 7) the memory gets put into a different state, and the code that 'worked' before now has random errors in it.

The ImageMagick guys haven't always taken invalid memory access as seriously as they should do in my opinion......feel free to ping me if they don't seem to grok the problem.

**Comment by vedmant** [comment]
Thanks, I tried to upgrade ghostscript library to latest, 9.18 but php started to crash with segmentation fault. It works normally only with 9.14 GS version.

Now valgrind points to ImageMagick in all cases, php56, php70, convert, however actual visible image error is still on php70.

I'll open issue in ImageMagick repository.

Attached reports here for in case.
[convert-2.txt](https://github.com/mkoppanen/imagick/files/107584/convert-2.txt)
[php56-2.txt](https://github.com/mkoppanen/imagick/files/107585/php56-2.txt)
[php70-2.txt](https://github.com/mkoppanen/imagick/files/107586/php70-2.txt)

**Comment by Danack** [comment]
cool, btw they'll probably want you to confirm the bug still happens on the latest version of ImageMagick.

**Comment by Danack** [comment]
I'm going to close this here.

This is something that can only be fixed by ImageMagick.
