### ISSUE TITLE
resizeImage causes lost of transparent data

### ISSUE THREAD

**Issue by mlocati** [mkoppanen/imagick#253]
Let's start with this image (courtesy of @justim), which is a PNG with a transparent background:

![input](https://user-images.githubusercontent.com/928116/45763428-b53e2100-bc30-11e8-84eb-1ae4532886dc.png)

With this code:

```php
$imagick = new Imagick();
$imagick->readimage('./input.png');
$imagick->writeimages('./output-1.jpg', 1);
```

We have this output (it's a JPG image with a white background)

![output-1](https://user-images.githubusercontent.com/928116/45763585-06e6ab80-bc31-11e8-8e59-d251081ee1f3.jpg)

BTW, if we resize the image and save it as JPG with this code:

```php
$imagick->resizeimage(300, 106, Imagick::FILTER_UNDEFINED, 1);
$imagick->writeimages('./output-2.jpg', 1);
```

we have this output (it's a JPG image with a black background):

![output-2](https://user-images.githubusercontent.com/928116/45763659-3990a400-bc31-11e8-8b1c-0b0f5acea315.jpg)

It seems that `resizeimage` changes the definition of the background color (we'd expect a JPG image with the same background color as we had prior to the resize).

**Comment by Danack** [comment]
I think the issue is that the image has an alpha channel, and absent instructions to do what you want, ImageMagick picks a not so good behaviour when removing the alpha channel.

For any input image that might have an alpha channel, when saving to a format that doesn't support alpha channel, if you're explicit about what you want to happen, the result is more likely to be what you want.

```
$imagick = new Imagick('./background2.png');
$imagick->setImageBackgroundColor('white');
$imagick->setImageAlphaChannel(\Imagick::ALPHACHANNEL_REMOVE);
$imagick->setImageFormat('jpg');
$imagick->writeimages("./output.jpg", false);
```

The underlying ImageMagick library does exactly what you tell it to do, through the Imagick api. This does mean some of the time, as it doesn't guess what you actually wanted to happen (unlike the command line tools that do), it will do the not right thing for you.

Trying to put default behaviours over the top of ImageMagick is not something that this extension can/should be doing, I think.

**Comment by mlocati** [comment]
I agree that imagemagick should not apply any complex logic, but still I'd expect that it behaves in a consistent way: why without resizing the image we have a white background and with resizing we have a black background? That's the question...

**Comment by Danack** [comment]
You'd need to ask the ImageMagick people at https://github.com/ImageMagick/ImageMagick as it is the ImageMagick 'wand' api that Imagick uses: https://imagemagick.org/api/magick-image.php

I'm entirely unsure why it would behave like that.

**Comment by mlocati** [comment]
I'm not 100% sure that posting there some PHP code of the imagick PHP extension would be ok: I'd need to show some code that uses imagemagick directly, but I absolutely don't know it...

**Comment by Danack** [comment]
If you're asking for advice, they are usually not that bad about giving it.

And almost all of the Imagick methods are named directly after the equivalent MagickWand api call, e.g. for resize. 

https://github.com/mkoppanen/imagick/blob/d57a444766a321fa226266f51f1f42ee2cc29cc7/imagick_class.c#L11065-L11089


For reference, there is some debug examples here: https://github.com/Danack/imagemagicktest/blob/master/67258.c but compiling stuff in C is pain, so probably see what their response is first.

**Comment by mlocati** [comment]
Don't worry about C stuff, I'm (also) a C programmer.

Here's the issue I just submitted: https://github.com/ImageMagick/ImageMagick/issues/1400
