### ISSUE TITLE
Call to undefined method Imagick::setImageInterpolateMethod()

### ISSUE THREAD

**Issue by LIXiangChen** [mkoppanen/imagick#258]
I'm using `php_imagick-3.4.3-7.2-ts-vc15-x86` and `ImageMagick-7.0.7-11-vc15-x86`.

$obj->**set**ImageInterpolateMethod() doesn't exist, but $obj->**get**ImageInterpolateMethod() can work.

**Comment by Danack** [comment]
So.....it looks like the cause is me trying to be clever.

For this one, I actually setup feature detection to do it 'properly'. It turns out that the way I set it up completely missed setting it up on Windows, and so it isn't available there.

I'm going to revert that feature detection and go back to using the release version to determine whether to include it or not, which is a worse way of doing things, but does at least work.

**Comment by Danack** [comment]
This is fixed for the next release of Imagick, which is imminent.
