### ISSUE TITLE
Issue with processing large images 

### ISSUE THREAD

**Issue by mikkoaf** [mkoppanen/imagick#263]
### Issue
When a server starts processing a large image, the process fails as ImageMagick uses multiple threads erroneously. 

### Workaround
There is a known work-around `export MAGICK_THREAD_LIMIT=1` found from this [article](http://www.daniloaz.com/en/high-cpu-load-when-converting-images-with-imagemagick/) which forces the process to use only one thread.

###  Workaround results
Using this workaround leads to the process to timeout when even larger images are introduced. A solution would be to enable multithread processing.

More information about the issue can be provided as needed.

**Comment by mikkoaf** [comment]
Version of OpenMP installed in the environment:
```
echo |cpp -fopenmp -dM |grep -i open
#define _OPENMP 201107
```

**Comment by Danack** [comment]
I strongly recommend not doing image processing inside a webserver, but instead to have a separate image processing box, where the code is run through the PHP cli where the multi-threaded ImageMagick code should work. 

This is particularly true for large images which take a long time to process.

An example of how to do this is in this project: https://github.com/Danack/ImagickContained/

> the process fails as ImageMagick uses multiple threads erroneously.

It fails because the threading technology inside ImageMagick is not designed to be used inside another program that is also using threading.

> More information about the issue can be provided as needed.

To set your expectations - only if someone provided a complete patch for solving the problems of using multi-threaded ImageMagick inside a webserver would I be spending any time looking at this, as I don't think it is a profitable area for me to spend my time as I don't think it is solvable, and has better workaround of doing the image processing in a separate background job.
