### ISSUE TITLE
Imagick does not work with relative filepaths under any version of PHP in Windows

### ISSUE THREAD

**Issue by LukeNZ** [mkoppanen/imagick#96]
This seems to be a major flaw in Imagick. It is not possible to open a file with Imagick if that file is defined relatively to your project directory. Instead, an `ImagickException` occurs:

    UnableToOpenBlob `/media/full/1556a6f114ca9f5.99071832.jpg': No such file or directory @ error/blob.c/OpenBlob/2657

Of course, if you define the filepath to the image absolutely:

    // create an Imagick instance
    $image = new \Imagick('H:/myproject/' . $this->fileinfo['filename']);

It works perfectly alright. I can confirm this is a bug using ImageMagick 3.1.2, under PHP5.6 on Windows 7.

This is a highly undesirable "feature", namely because I switch between Windows & *nix development environments frequently. More worrisome is the fact that this appears [to have been a bug since at least 2012](https://bugs.php.net/bug.php?id=61583), and has remained unfixed.

Any chance of a fix soon? I would do a PR myself and fix it but I'm a junior dev anyway so it's mainly out of my depth.

**Comment by Danack** [comment]
Ok...so:

i) `"/media/full/1556a6f114ca9f5.99071832.jpg"` is not a relative path, you probably meant `"./media/full/1556a6f114ca9f5.99071832.jpg"

ii) You can resolve the full path yourself using realpath(). Imagick can't do this trivially as "file names" can actually be urls, or combination of filenames + with page reference e.g. `"./SQTimetable.pdf[2]"` tells ImageMagick to open the second page of file "SQTimetable.pdf"

iii) Relative paths actually work....just not in ZTS PHP. 


This possible could be made to work for ZTS mode by adding a VCWD resolve.

```
if (VCWD_REALPATH(filename, resolved_path_buff)) {
		if (php_check_open_basedir(resolved_path_buff TSRMLS_CC)) {
			RETURN_FALSE;
		}
}
```

which I'll think about for next version.

**Comment by Danack** [comment]
After having thought about this for a while - I'm not going to attempt to change it.

It is trivial to call realpath in userland, and pass absolute file names to Imagick.

Trying to handle things like "./SQTimetable.pdf[2]" are absolutely not trivial - in fact I'm not sure how it could be handled. 

Rather than creating a whole load of work, just to solve something that already has a userland solution, I'm just going to update the documentation to be clearer that only absolute file names are supported.
